version: "3"
networks:
  nocobase:
    driver: bridge
services:
  verdaccio:
    image: verdaccio/verdaccio
    networks:
      - nocobase
    environment:
      VERDACCIO_PORT: 9973
    restart: always
    ports:
      - "9973:9973"
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "9974:3306"
    networks:
      - nocobase
  postgres:
    image: postgres:10
    restart: always
    networks:
      - nocobase
    command: postgres -c wal_level=logical
    ports:
      - "9975:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  adminer:
    image: nocobase/adminer
    restart: always
    networks:
      - nocobase
    ports:
      - "9976:8080"
    volumes:
      - ./:/var/www/app
  nocobase:
    image: node:16-stretch-slim
    networks:
      - nocobase
    command: [ "yarn", "start" ]
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    expose:
      - 9977
    ports:
      - "9977:9977"
