version: "3"
networks:
  nocobase:

services:
  app:
    image: nocobase/nocobase:main
    networks:
      - nocobase
    environment:
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
